import { Task, PathStage } from './types';

export const TASKS: Task[] = [
  {
    id: 'webdev1',
    name: 'Web Dev',
    subtitle: 'Morning Session',
    time: '8:15 – 10:30 AM',
    duration: '2h 15m',
    color: '#3b82f6',
    icon: 'Code',
    path: true,
    category: 'learning',
  },
  {
    id: 'aiml',
    name: 'AI / ML',
    subtitle: 'Study Block',
    time: '12:00 – 1:30 PM',
    duration: '1h 30m',
    color: '#8b5cf6',
    icon: 'Brain',
    path: false,
    category: 'learning',
  },
  {
    id: 'clg',
    name: 'College Study',
    subtitle: 'rotating subject',
    time: '3:30 – 4:30 PM',
    duration: '1h',
    color: '#10b981',
    icon: 'BookOpen',
    path: false,
    category: 'college',
    rotating: true,
  },
  {
    id: 'dsa',
    name: 'DSA',
    subtitle: 'Problem Solving',
    time: '6:30 – 8:00 PM',
    duration: '1h 30m',
    color: '#f59e0b',
    icon: 'Layers',
    path: false,
    category: 'learning',
  },
  {
    id: 'webdev2',
    name: 'Web Dev',
    subtitle: 'Evening Session',
    time: '8:30 – 9:30 PM',
    duration: '1h',
    color: '#3b82f6',
    icon: 'Code',
    path: true,
    category: 'learning',
  },
  {
    id: 'webdev3',
    name: 'Web Dev',
    subtitle: 'Night Session',
    time: '11:45 PM – 2:00 AM',
    duration: '2h 15m',
    color: '#3b82f6',
    icon: 'Code',
    path: true,
    category: 'learning',
  },
];

export const SUBJECTS = ['DBMS', 'CN', 'DDBMS', 'Pattern Recognition'];

export const PATH_STAGES: PathStage[] = [
  {
    id: 'html',
    name: 'HTML',
    source: 'freeCodeCamp',
    color: '#e34c26',
    description: 'Structure & semantics',
  },
  {
    id: 'js',
    name: 'JavaScript',
    source: 'freeCodeCamp + MDN',
    color: '#f0db4f',
    description: 'Core language & DOM',
  },
  {
    id: 'react',
    name: 'React JS',
    source: 'Official Docs + Projects',
    color: '#61dafb',
    description: 'Components & state',
  },
  {
    id: 'practice',
    name: 'Practice',
    source: 'Build real projects',
    color: '#10b981',
    description: 'Apply everything',
  },
];